// Code generated by Kitex v0.9.1. DO NOT EDIT.

package noteservice

import (
	"context"
	note "easy_note/kitex_gen/note/note"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	CreateNote(ctx context.Context, req *note.CreateNoteReq, callOptions ...callopt.Option) (r *note.CreateNoteResp, err error)
	DeleteNote(ctx context.Context, req *note.DeleteNoteReq, callOptions ...callopt.Option) (r *note.DeleteNoteResp, err error)
	UpdateNote(ctx context.Context, req *note.UpdateNoteReq, callOptions ...callopt.Option) (r *note.UpdateNoteResp, err error)
	MGetNote(ctx context.Context, req *note.MGetNoteReq, callOptions ...callopt.Option) (r *note.MGetNoteResp, err error)
	QueryNote(ctx context.Context, req *note.QueryNoteReq, callOptions ...callopt.Option) (r *note.QueryNoteResp, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfoForClient(), options...)
	if err != nil {
		return nil, err
	}
	return &kNoteServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNoteServiceClient struct {
	*kClient
}

func (p *kNoteServiceClient) CreateNote(ctx context.Context, req *note.CreateNoteReq, callOptions ...callopt.Option) (r *note.CreateNoteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.CreateNote(ctx, req)
}

func (p *kNoteServiceClient) DeleteNote(ctx context.Context, req *note.DeleteNoteReq, callOptions ...callopt.Option) (r *note.DeleteNoteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteNote(ctx, req)
}

func (p *kNoteServiceClient) UpdateNote(ctx context.Context, req *note.UpdateNoteReq, callOptions ...callopt.Option) (r *note.UpdateNoteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateNote(ctx, req)
}

func (p *kNoteServiceClient) MGetNote(ctx context.Context, req *note.MGetNoteReq, callOptions ...callopt.Option) (r *note.MGetNoteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.MGetNote(ctx, req)
}

func (p *kNoteServiceClient) QueryNote(ctx context.Context, req *note.QueryNoteReq, callOptions ...callopt.Option) (r *note.QueryNoteResp, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.QueryNote(ctx, req)
}
